### ISSUE TITLE
find-by-key, with a bad key, throws an exception in sql and returns nil in memory

### ISSUE THREAD

**Issue by trptcolin** [8thlight/hyperion#18]
What should the contract be for `find-by-key`, when the key is garbage? Should it: (a) return nil? (my preference), or (b) throw an exception when trying to decompose the key?

Currently, using the sql datastore in this way causes an exception to be thrown (see below), but application tests using the memory store do not expose this behavior (since they don't decompose keys the same way?).

There are several ways it's easy to encounter this error:
1. nil key (easy to check with code like this: `(if key (find-by-key key) nil)`
2. empty-string key (similarly easy, but takes an extra function call, maybe pulling in `clojure.string/blank?`)
3. key constructed incorrectly by using the more human-readable database foreign key 

I can understand if #3 needs to be out of scope, but it seems to me that #1 and #2 are code that everyone will have to write on every find-by-key call when the key comes from user input (via web pages or other means) - so they seem desirable to be built in.

```
java.lang.ArrayIndexOutOfBoundsException: -1
        at clojure.data.codec.base64$pad_length.invokePrim(base64.clj:53)
        at clojure.data.codec.base64$decode.invokePrim(base64.clj:146)
        at clojure.data.codec.base64$decode.invoke(base64.clj:144)
        at hyperion.key$decode_key.invoke(key.clj:16)
        at hyperion.key$decompose_key.invoke(key.clj:29)
        at hyperion.sql.key$decompose_key.invoke(key.clj:11)
        at hyperion.sql.SQLDatastore.ds_find_by_key(sql.clj:56)
        at hyperion.api$find_by_key.invoke(api.clj:320)
        at hosemonster.accounts.accounts_controller$load_account.invoke(accounts_controller.clj:19)
        at hosemonster.accounts.accounts_controller$save_account.invoke(accounts_controller.clj:24)
        at hosemonster.accounts.accounts_controller$fn__8332$fn__8351.invoke(accounts_controller.clj:70)
```

**Comment by mylesmegyesi** [comment]
Colin - thanks for the info. I will build #1 and #2 into `find-by-key`. The contract will be to return `nil`, which is the same as if the record does not exist.

I'm not sure I understand #3 fully. Could you give me an example?

**Comment by trptcolin** [comment]
Awesome, thanks! 

For #3, I was just thinking about the "user error" category of things. Maybe another (non-hyperion-using) service is reading the same database, or maybe someone doesn't understand how things work. For instance, I originally tried using the foreign key from the database as input to `find-by-key`, and was surprised/confused by the error, especially since it surfaced w/ the SQL datastore and not the memory one that I used in my unit tests. Also since the error is at a relatively low level, `ArrayIndexOutOfBoundsException` and users might need a bit of implementation context to reason about what causes it.

I'm not sure whether the right solution is to have the exception thrown at a higher level, or to catch it and return nil, or something else. 

But as long as I can catch these kinds of problems easily in my memory store tests, I'm happy.

**Comment by mylesmegyesi** [comment]
What was the input that caused the `ArrayIndexOutOfBoundsException` above? I'm having trouble replicating it.

**Comment by trptcolin** [comment]
Sorry, looks like that exception was from `(find-by-key "")` - `(find-by-key "foo")` throws this one:

```
Exception Invalid key form: ?
        hyperion.key/decompose-key (key.clj:32)
        hyperion.sql.key/decompose-key (key.clj:11)
        hyperion.sql.SQLDatastore (sql.clj:56)
        hyperion.api/find-by-key (api.clj:320)
        hosemonster.repl/eval3073 (NO_SOURCE_FILE:1)
```

**Comment by mylesmegyesi** [comment]
Thanks!

Myles

**Comment by mylesmegyesi** [comment]
fixed in master.
