### ISSUE TITLE
restrict save api

### ISSUE THREAD

**Issue by ghost** [8thlight/hyperion#22]
There are too many similar ways to save which makes it difficult to memorize just one of them, and I've often guessed ways to call the function that seem intuitive and have failed. Having one single, canonical way to use the save function would make this problem disappear like fog in the sunlight or Bert Reynolds' career.

**Comment by slagyr** [comment]
Too many ways?  I only count 1 way.

(save thing [optional fields])

**Comment by ghost** [comment]
Taken from the README:

``` clojure
(save {:kind :foo})
;=> {:kind "foo" :key "generated key"}
(save {:kind :foo} {:value :bar})
;=> {:kind "foo" :value :bar :key "generated key"}
(save {:kind :foo} :value :bar)
;=> {:kind "foo" :value :bar :key "generated key"}
(save {:kind :foo} {:value :bar} :another :fizz)
;=> {:kind "foo" :value :bar :another :fizz :key "generated key"}
(save (citizen) :name "Joe" :age 21 :country "France")
;=> #<{:kind "citizen" :name "Joe" :age 21 :country "France" ...}>
```

Perhaps it's an imagined problem. I just know that I tried (save :mykind :mykey "myval") and it didn't work. I'm not suggesting this become another acceptable way to call #'save, I'm saying that my guess resulted from there being so many ways in the first place.

But maybe more flexible is better, and maybe this issue should just be closed. I don't know.
