### ISSUE TITLE
Renaming entities impractical

### ISSUE THREAD

**Issue by sdegutis** [8thlight/hyperion#24]
@mylesmegyesi @slagyr

I could be wrong, but I think you can't easily rename mongo collections when using hyperion because of the way hyperion stores the type in its keys. It would require a migration that finds every reference to the old keys and updates them to the new keys. Is this correct, or is there another way?

**Comment by slagyr** [comment]
@evanescence  Yeah… that's right.  The name of the collection/kind is stored in the keys. It would be challenging to rename a collection when it's already populated with data and keys to that data are referenced from other collections.

So could hyperion avoid storing collections names in the keys?  The only way I can think of is to persist a meta-table that maps kind to collection.  That sounds hairy too.

**Comment by mylesmegyesi** [comment]
If you use the [`foreign-key`](https://github.com/8thlight/hyperion#foreign-keys) type with a `defentity`, the kind will _not_ be stored in the key.

**Comment by sdegutis** [comment]
@slagyr No, the collection name needs to remain inside the key to allow polymorphism. For example a "payments" list could have one key linking to an object in "cash-payment" collection, and another key linking to an object in "credit-card-payment" collection. This is too useful a feature to give up just to make renaming collections easier.

**Comment by sdegutis** [comment]
Also @mylesmegyesi I could be mistaken but I think that's not true about the mongodb store, I think it actually stores the raw hyperion key as the literal mongo key (_id).

**Comment by sdegutis** [comment]
@slagyr I just edited my last comment to reference your name, but I don't know if editing comments to include a reference will ping that person. Hence this comment.

**Comment by mylesmegyesi** [comment]
@evanescence it looks like you're right about mongo. It does not unpack keys.

**Comment by sdegutis** [comment]
@slagyr @mylesmegyesi 

Some new thoughts on this subject:

There's three benefits to looking up an entity by key without specifying the collection. But I don't think we need any of these benefits.

The first one is that you can omit the collection name, which lets you do polymorphism. But nearly everywhere in my code, when I'm calling (find-by-key), I already know exactly what type it's going to be, which means I already know exactly what collection it's going to come from. So I could easily specify the collection name in those places. And in the places I don't know, I can store the kind name in the database alongside the key.

The second one is related, it's a specific case of polymorphism based on to-many relationships. Let's say you have an "order" which has an array of keys to either "cash-payment" or "credit-card-payment". Because Hyperion stores the collection within the name, it can figure out which collection to look it up from. But again, the developer could get this polymorphism from just storing the collection name next to the key.

The third one is that having the collection name allows Hyperion to pack/unpack keys properly, and ensure that only the specified keys are saved to the backing store. But because you're specifying the collection name on find-by-key, you can still get that behavior. And as long as you still use :kind, you can still get that behavior on (save) too.

There's two benefits. The smaller one is that keys can literally just be a dead simple type (auto-incrementing integers, UUIDs, whatever). But more importantly, renaming collections becomes a ton easier. And that's a really big plus when you want to be Agile.

Granted, if this change is made, the API becomes backwards-incompatible. If it were just code changes, I'd say just force people to upgrade. But it also requires structuring your data differently, and there are already existing users with lots of data. Perhaps such an API change merits becoming a separate project?

**Comment by mylesmegyesi** [comment]
@evanescence I think you have some valuable points. I'm certainly open to the change. However the Hyperion API is very stable at this point, mostly because of data, as you mentioned. I believe that a departure from the API as large as this would warrant a separate project, unfortunately.
