### ISSUE TITLE
Nested results?

### ISSUE THREAD

**Issue by davejacobs** [8thlight/hyperion#26]
I have a fully normalized Postgres database, and I'm trying to decide if Hyperion can help me clean up low-level Korma code I'm using now for database interaction. One thing I would need is to get back nested results that are the results of joins. Is there a way to (after specifying entity relationships via `defentity`) get back nested results from a query?

I would love to do something like `(find-by-kind :users)` and get back related address, etc. Is this possible, or should I stick with Korma?

**Comment by slagyr** [comment]
Hyperion doesn't do joins.  This is because Hyperion aims to provide a simple API that'll apply to (almost) any database.  Since lots of databases, especially nosql databases, don't have joins, Hyperion doesn't support them.

Hope this helps.

**Comment by davejacobs** [comment]
Gotcha, thanks.
