### ISSUE TITLE
find-by-kind :filters does not work with multiple filters on mongo

### ISSUE THREAD

**Issue by paytonrules** [8thlight/hyperion#30]
At least on a current project this:

```
(find-by-kind :project :filters [[:= :name "My Project"] [:!= :key "cHJvamVjdDozRW9pajRCYw"]])
```

returns:

```
({:kind "project", :key "cHJvamVjdDozRW9pajRCYw", :name "My Project", :code "prj", :permaname "my-project", :logo-key nil, :default-template-key nil, :created-at #inst "2014-08-04T14:20:11.097-00:00", :updated-at #inst "2014-08-04T14:20:11.097-00:00"})
```

The project should have been filtered out. Note this works properly against the in-memory driver.

**Comment by aspalding** [comment]
I was able to reproduce this and isolate the problem to only include filtering by key. 

```
(it "Can filter by key." 
  (let [project (save {:kind :project :name "My Project"})
        my-key (:key project)
        found-not-equals (find-by-kind :project :filters [:!= :key my-key])]
    (should-not-contain project found-not-equals)))
```

This applies for filtering by equals as well as not equals. 

The test will pass if dorun is called while accessing the project hash.

```
(it "Can filter by key." 
  (let [project (save {:kind :project :name "My Project"})
        my-key (dorun (:key project))
        found-not-equals (find-by-kind :project :filters [:!= :key my-key])]
    (should-not-contain project found-not-equals)))
```

If you have the key to the record you're searching its probably preferable to use find-by-key. I was able to  query with multiple filters successfully using other values stored in the record.

**Comment by mylesmegyesi** [comment]
The [docs](https://github.com/8thlight/hyperion#filters-and-sorts) state that filtering and sorting on `:key` is not supported. The only _supported_ way to search on `:key` is with `find-by-key`. If you really need this functionality, I would gladly merge a pull request.

**Comment by paytonrules** [comment]
Then the problem is in the in-memory-datastory, it will filter by key properly. This causes misleading tests.

—
